version: '3'

services:
  api:
    container_name: bitespeed-api
    image: bitespeed-api:latest
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
